#spring.config.import=optional:file:.env[properties]

spring.application.name=CredenceBank

server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/credencebank
spring.datasource.username=root
spring.datasource.password=Samiksha@7020

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


#JWT Configuration
jwt.secret.string = credenceBankProjectSecretKeyCredenceBank2026
jwt.expiration.time=2592000000

#Mail Configuration
spring.mail.username=credencebank.app@gmail.com
spring.mail.password=qzen bovx ubrv jazm
spring.mail.host=smtp.gmail.com
spring.mail.port=587

#Enable TLS SMTP MAIL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

password.reset.link=http://bank-fn-deploy.s3-website.us-east-2.amazonaws.com/reset-password?code=


